version: "3.9"

services:
  retropilot-server:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - retropilot-data:/etc/retropilot
    env_file:
      - server-variables.env

volumes:
  retropilot-data:
