version: "3.9"

services:
  retropilot-server:
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - .:/etc/retropilot
    env_file:
      - server-variables.env
  retropilot-worker:
    build: .
    command: /usr/local/bin/node worker.js
    restart: unless-stopped
    volumes:
      - .:/etc/retropilot
    env_file:
      - server-variables.env
